# Site settings
title: OSH
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Paul
user_description: Life is just once. Let's try anything. Just do it. Most important thing is loving other people.
user_title: Freedom
email: rnvl1236@gmail.com
# github_username:  paul7958


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
